import {MatButtonModule,
   MatCheckboxModule,
   MatSidenavModule,
   MatIconModule,
   MatToolbarModule,
   MatListModule,
   MatDialogModule,
   MatCardModule,
   MatDatepickerModule,
   MatNativeDateModule,
   MatTooltipModule,
   MatAutocompleteModule,
   MatDividerModule,
   MatInputModule,
   MatFormFieldModule,
   MatTableModule,
   MatGridListModule,
   MatTabsModule,
   MatSnackBarModule,
   MatRippleModule,
   MatPaginatorModule,
   MatMenuModule} from '@angular/material';
   import {ScrollDispatchModule} from '@angular/cdk/scrolling';
import { NgModule } from '@angular/core';

@NgModule({
  imports: [
    MatButtonModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatMenuModule,
    MatIconModule,
    MatToolbarModule,
    MatListModule,
    MatDialogModule,
    MatCardModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTooltipModule,
    MatAutocompleteModule,
    MatDividerModule,
    MatInputModule,
    MatFormFieldModule,
    MatTableModule,
    MatGridListModule,
    MatSnackBarModule,
    MatRippleModule,
    MatPaginatorModule,
    MatTabsModule,
    ScrollDispatchModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatMenuModule,
    MatIconModule,
    MatToolbarModule,
    MatListModule,
    MatDialogModule,
    MatCardModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTooltipModule,
    MatAutocompleteModule,
    MatDividerModule,
    MatInputModule,
    MatFormFieldModule,
    MatTableModule,
    MatGridListModule,
    MatSnackBarModule,
    MatRippleModule,
    MatPaginatorModule,
    MatTabsModule,
    ScrollDispatchModule
  ],
})
export class MyOwnCustomMaterialModule { }
